all: churn parser spilt_file week_of_churn

churn: churn.c
	gcc -o churn churn.c 

parser: parser.c 
	gcc -o parser parser.c

spilt_file: spilt_file.c
	gcc -o spilt_file spilt_file.c 
	
week_of_churn: week_of_churn.c
	gcc -o week_of_churn week_of_churn.c 